# Generated by Django 5.1 on 2024-11-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('Id_Cliente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=100)),
                ('Apellidos', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=100)),
                ('Fecha_Nac', models.CharField(max_length=100)),
                ('Edad', models.IntegerField()),
                ('Telefono', models.CharField(max_length=100)),
            ],
        ),
    ]
